name: paper-agent
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision=0.15.2
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - tqdm=4.66.1
  - pyyaml=6.0.1
  - pip=23.1.2
  - pip:
    - openai==1.13.3
    - anthropic==0.8.1
    - google-generativeai==0.3.2
    - langchain==0.0.267
    - transformers==4.35.0
    - tiktoken==0.5.2
    - aiohttp==3.9.1
    - asyncio==3.4.3
    - python-dotenv==1.0.0
    - pylatex==1.4.1 